include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # This tells the analyzer to globally ignore the
    # "missing_permission" warning that is causing all the errors.
    missing_permission: ignore