// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos- '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoDBC1NhBhvAdZ7dUeP692zqJzFdZ_PzU',
    appId: '1:327469030653:android:9253b654f7b4d81e73b294',
    messagingSenderId: '327469030653',
    projectId: 'agelink-f4680',
    storageBucket: 'agelink-f4680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRUi3V0QfmXYzj72c6O1Jy_UyG5-1IwxE',
    appId: '1:327469030653:ios:3d66147e90b86e9e73b294',
    messagingSenderId: '327469030653',
    projectId: 'agelink-f4680',
    storageBucket: 'agelink-f4680.firebasestorage.app',
    androidClientId: '327469030653-rjqul9vt5mpnecmngf2665ilngck3u9g.apps.googleusercontent.com',
    iosClientId: '327469030653-ucvns77jb8q23aebrf5hs8oj4dlb222d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ageLink',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3E1VVnvaZkyz5f3Z1uyXsKlXklALw6MI',
    appId: '1:327469030653:web:2d4ab3db1ead1f6373b294',
    messagingSenderId: '327469030653',
    projectId: 'agelink-f4680',
    authDomain: 'agelink-f4680.firebaseapp.com',
    storageBucket: 'agelink-f4680.firebasestorage.app',
  );

}